---
name: run_ansible_playbook
description: Run ansible playbook
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    description: "Run playbook with sudo"
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  timeout:
    default: 180
  cmd:
    description: "Command to run"
    immutable: false
    # inventory-file ec2.py is now defined in /root/.ansible.cfg
    default: "/opt/stackstorm/virtualenvs/ansible/bin/ansible-playbook /opt/stackstorm/packs/${ST2_ACTION_PACK_NAME}/playbooks/{{playbook}}.yaml --extra-vars='tag={{tag}} env={{env}}'"
  playbook:
    description: "Ansible playbook to run"
    type: string
    required: true
  tag:
    description: "AWS tag used to identify what hosts to run the ansible playbook"
    type: string
    required: true
  env:
    description: "AWS env tag to limit what hosts to run the ansible playbook"
    type: string
    required: true
