- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get ELB facts
      local_action:
        module: ec2_elb_facts
        names: "{{ elb_name }}"
        region: us-east-1
        aws_access_key: xxxxxxxxxxxxxxxxx
        aws_secret_key: xxxxxxxxxxxxxxxxx
        region: us-east-1
      register: elb
    - name: debug
      debug: msg="{{ elb }}"
