---
- hosts: "{{ tag }}:&tag_env_{{ environment }}"
  gather_facts: false
  tasks:
    - name: get hostname
      shell: hostname -f
      register: hostname
    - name: get disk usage
      shell: df -h
      register: df
    - name: get uptime
      shell: uptime
      register: uptime
    - name: output hostname
      debug: msg="{{ hostname.stdout }}"
    - name: output df
      debug: msg="{{ df.stdout }}"
    - name: output uptime
      debug: msg="{{ uptime.stdout }}"
