---
- hosts: "{{ tag }}:&tag_env_{{ environment }}"
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Search catalina logs
      shell: cat /var/log/tomcat8/catalina.out |grep {{ search_term }}
      register: logs
    - name: output logs
      debug: msg="{{ logs.stdout }}"
